In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[2525, 725, 264, 840],
 [2525, 725, 264, 9496],
 [2525, 1827, 264, 7056],
 [4275, 4256, 6601, 9391, 4351],
 [4275, 4256, 6601, 9391, 2727],
 [574, 2525, 7419, 264, 7115],
 [4690, 9576, 5115, 9391]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2525  725  264  840]
 [   0    0    0    0 2525  725  264 9496]
 [   0    0    0    0 2525 1827  264 7056]
 [   0    0    0 4275 4256 6601 9391 4351]
 [   0    0    0 4275 4256 6601 9391 2727]
 [   0    0    0  574 2525 7419  264 7115]
 [   0    0    0    0 4690 9576 5115 9391]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

d:\UdemyKN\Deep Learning NLP\deep\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 165ms/step


array([[[-0.01716837,  0.01606959, -0.00584415, -0.02690777,
         -0.00127803, -0.0087003 ,  0.02473776,  0.02286145,
          0.03085256, -0.04609454],
        [-0.01716837,  0.01606959, -0.00584415, -0.02690777,
         -0.00127803, -0.0087003 ,  0.02473776,  0.02286145,
          0.03085256, -0.04609454],
        [-0.01716837,  0.01606959, -0.00584415, -0.02690777,
         -0.00127803, -0.0087003 ,  0.02473776,  0.02286145,
          0.03085256, -0.04609454],
        [-0.01716837,  0.01606959, -0.00584415, -0.02690777,
         -0.00127803, -0.0087003 ,  0.02473776,  0.02286145,
          0.03085256, -0.04609454],
        [ 0.01940035, -0.04082278,  0.04059752,  0.01226328,
          0.04282281,  0.04339894,  0.03030184, -0.03553377,
          0.01512544,  0.00597333],
        [-0.03448479, -0.03947832, -0.03034493,  0.03053676,
         -0.01697487,  0.04507772,  0.04879353,  0.04575563,
          0.0246873 ,  0.03096732],
        [ 0.01734305,  0.03705932, -0.03389581, -0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 2525,  725,  264,  840], dtype=int32)

In [18]:
model.predict(embedded_docs[1:2])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step


array([[[-0.01716837,  0.01606959, -0.00584415, -0.02690777,
         -0.00127803, -0.0087003 ,  0.02473776,  0.02286145,
          0.03085256, -0.04609454],
        [-0.01716837,  0.01606959, -0.00584415, -0.02690777,
         -0.00127803, -0.0087003 ,  0.02473776,  0.02286145,
          0.03085256, -0.04609454],
        [-0.01716837,  0.01606959, -0.00584415, -0.02690777,
         -0.00127803, -0.0087003 ,  0.02473776,  0.02286145,
          0.03085256, -0.04609454],
        [-0.01716837,  0.01606959, -0.00584415, -0.02690777,
         -0.00127803, -0.0087003 ,  0.02473776,  0.02286145,
          0.03085256, -0.04609454],
        [ 0.01940035, -0.04082278,  0.04059752,  0.01226328,
          0.04282281,  0.04339894,  0.03030184, -0.03553377,
          0.01512544,  0.00597333],
        [-0.03448479, -0.03947832, -0.03034493,  0.03053676,
         -0.01697487,  0.04507772,  0.04879353,  0.04575563,
          0.0246873 ,  0.03096732],
        [ 0.01734305,  0.03705932, -0.03389581, -0.0